name: HardcoreMode
version: 1.0.0
main: com.eofitg.hardcore.Hardcore
api-version: 1.18
authors: [ eofitg ]
description: Add hardcore mode to server.

commands:
  hardcore:
    aliases: [ hardcoremode ]
    description: HardcoreMode plugin's setup and management.
    usage: /hardcore help